GAIN-10: Fixed a SigMFDTypeInfo BUG
ValueError: mutable default <class 'dict'> for field _dtype_dict is not allowed: use default_factory

Fixed(?)

Changes to be committed:
	modified:   gallant_input/sigmfdtypeinfo.py

Changes not staged for commit:
	modified:   gallant_input/sigmfmetabuilder.py
	modified:   gallant_input/sigmfmetaparser.py