GAIN-16: Fixed small QPSKConfig() BUG
The default factory expects a callable but it was getting a dict by
default.

TypeError: 'dict' object is not callable

Fixed.

Changes to be committed:
	modified:   gallant_input/modem/qpsk_config.py

Untracked files:
	test/unit_test/test_modem/test_qpsk/test_modem_qpsk_demodulate.py