GAIN-2: Continued implementing arg parser
EOD Commit (again!)

- Made the Linters happy (then angered them a bit)
- (Mostly) Finished implementing on command arg parser
- Continued implemening main() (to manually test arg parser)

BUGS TO FIX:
	* --debug doesn't work (add it to both sub-commands)
	* Debugging Logger usage has unexpected output (see: Logger.error() output is doubled)
	* See below

As of this commit, this command...
python -m gallant_input --debug analyze --basename file
...resulted in this output...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/app/gallant-input/gallant_input/__main__.py", line 16, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/gallant-input/gallant_input/main.py", line 39, in main
    Logger.error('ERROR!')
  File "/app/gallant-input/gallant_input/logger.py", line 127, in error
    logging.getLogger(logger).error(message)
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1518, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.11/logging/__init__.py", line 1705, in callHandlers
    if record.levelno >= hdlr.level:
                         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'level'

Changes to be committed:
	modified:   gallant_input/arg_parser.py
	modified:   gallant_input/main.py